# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "fd3961af615f16cfb9d4e22854b9f7e9"
application_url = "https://ai-store-scanner.vercel.app"
embedded = true
name = "AI Store Scanner"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products, read_orders, read_customers, read_themes, read_discounts, read_content, read_legal_policies"

[webhooks]
api_version = "2026-10"

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/uninstalled"
  topics = [ "app/uninstalled" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/scopes_update"
  topics = [ "app/scopes_update" ]

  [webhooks.privacy_compliance]
  customer_data_request_url = "/webhooks/customers/data_request"
  customer_deletion_url = "/webhooks/customers/redact"
  shop_deletion_url = "/webhooks/shop/redact"

[auth]
redirect_urls = [ "https://ai-store-scanner.vercel.app/auth/callback" ]

[build]
automatically_update_urls_on_dev = true
