export default function Terms() {
  return (
    <div style={{ maxWidth: "40rem", margin: "0 auto", padding: "3rem 1.5rem", fontFamily: "sans-serif", lineHeight: 1.6 }}>
      <h1>Terms of Service</h1>
      <p>Last updated: {new Date().toISOString().slice(0, 10)}</p>

      <h2>The service</h2>
      <p>
        AI Store Scanner (&quot;the app&quot;) scans data from your Shopify store and uses
        Anthropic&apos;s Claude API to generate feature and growth recommendations. Features
        you request from a scan are tracked in a build queue for follow-up. By installing
        the app, you agree to these terms.
      </p>

      <h2>Subscription plans and billing</h2>
      <ul>
        <li>The app offers three subscription plans &mdash; Basic, Pro, and Growth &mdash; each with a different monthly store-scan allowance.</li>
        <li>All charges are billed and processed through Shopify&apos;s Billing API on a recurring 30-day cycle. We do not collect or store payment card details ourselves.</li>
        <li>You can change or cancel your plan at any time from the app&apos;s Settings page or from your Shopify admin&apos;s app subscription management.</li>
        <li>Charges already billed for the current period are not refunded on downgrade or cancellation; your plan remains active until the end of the paid period.</li>
        <li>Prices are shown in USD and may be updated with advance notice; continued use of the app after a price change constitutes acceptance of the new price.</li>
      </ul>

      <h2>Your Anthropic API key</h2>
      <p>
        Store scans require an Anthropic API key, which you provide and manage in Settings.
        Any usage costs charged by Anthropic for your key are your responsibility and are
        separate from your AI Store Scanner subscription. If you don&apos;t provide a key,
        scans may fall back to a shared key with a limited daily scan allowance.
      </p>

      <h2>Acceptable use</h2>
      <p>
        You agree not to use the app to violate Shopify&apos;s Acceptable Use Policy, attempt
        to circumvent scan or billing limits, or use the service for any unlawful purpose.
        We may suspend access for accounts that abuse the service or fail to maintain an
        active subscription.
      </p>

      <h2>No warranty</h2>
      <p>
        Recommendations generated by the app are AI-generated suggestions based on your
        store&apos;s data and are provided for informational purposes only. We do not
        guarantee their accuracy, completeness, or business impact, and you are responsible
        for evaluating any recommendation before acting on it. The app is provided
        &quot;as is&quot; without warranties of any kind.
      </p>

      <h2>Limitation of liability</h2>
      <p>
        To the maximum extent permitted by law, we are not liable for any indirect,
        incidental, or consequential damages arising from your use of the app, including
        lost revenue or data, except where such liability cannot be excluded by law.
      </p>

      <h2>Termination</h2>
      <p>
        You may uninstall the app at any time, which cancels your subscription and triggers
        deletion of your shop&apos;s data as described in our{" "}
        <a href="/privacy">Privacy Policy</a>. We may suspend or terminate access to the app
        for violations of these terms.
      </p>

      <h2>Changes to these terms</h2>
      <p>
        We may update these terms from time to time. Continued use of the app after changes
        are posted constitutes acceptance of the updated terms.
      </p>

      <h2>Contact</h2>
      <p>
        Questions about these terms? Reach us on{" "}
        <a href="https://www.facebook.com/DevComDMS" target="_blank" rel="noreferrer">
          Facebook
        </a>
        .
      </p>

      <h2>Related</h2>
      <p>
        See also our <a href="/privacy">Privacy Policy</a>.
      </p>
    </div>
  );
}
